apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "dumarkovohc"
    cloudName: "AzurePublicCloud" 
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret  
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret 
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret   
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
