apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "ohcontainersteam1"
    cloudName: "AzurePublicCloud" 
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret  
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret 
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret   
    tenantId: "030fe529-7e2f-4cb1-97bc-1740e7feff07"
