apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: dumarkovohc.azurecr.io/api/tripviewer:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.api"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api" 
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"              
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tripviewer
