apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrywlz8634.azurecr.io/tripinsights/userprofile:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: SQL_USER
          value: sqladminwLz8634
        - name: SQL_PASSWORD
          value: rX8hh5Ga6
        - name: SQL_SERVER
          value: sqlserverwlz8634.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
      # volumes:
      #   - name: secrets-store-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "azure-kvname"
      #       nodePublishSecretRef:
      #         name: secrets-store-creds           
---
apiVersion: v1
kind: Service
metadata: 
  name: userprofile
spec: 
  type: ClusterIP #LoadBalancer 
  ports: 
  - port: 80 
    targetPort: 80
  selector: 
    app: userprofile

           
           
           